global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using FramesBlazor.Models;
global using FramesBlazor.Data;
global using Radzen;
global using Radzen.Blazor;
global using FramesBlazor.Contracts;
global using System.Linq.Dynamic.Core;